package pl.tzaras.fitness.manager.db.data;

// Generated Nov 11, 2013 11:05:25 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import org.joda.time.DateTime;

/**
 * GymClass generated by hbm2java
 */
public class GymClass implements java.io.Serializable {

	private long classId;
	private GymRoom classRoom;
	private GymClassType classType;
	private DateTime startTime;
	private long duration;
	private int participants;
	private Set<GymTrainer> trainers = new HashSet<GymTrainer>(0);

	public GymClass() {
	}

	public GymClass(GymRoom classRoom, GymClassType classType) {
		this.classRoom = classRoom;
		this.classType = classType;
	}

	public GymClass(GymRoom classRoom, GymClassType classType, DateTime startTime, long duration,
			int participants, Set<GymTrainer> trainers) {
		this.classRoom = classRoom;
		this.classType = classType;
		this.startTime = startTime;
		this.duration = duration;
		this.participants = participants;
		this.trainers = trainers;
	}

	public long getClassId() {
		return this.classId;
	}

	public void setClassId(long classId) {
		this.classId = classId;
	}

	public GymRoom getClassRoom() {
		return this.classRoom;
	}

	public void setClassRoom(GymRoom classRoom) {
		this.classRoom = classRoom;
	}

	public GymClassType getClassType() {
		return this.classType;
	}

	public void setClassType(GymClassType classType) {
		this.classType = classType;
	}

	public DateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(DateTime startTime) {
		this.startTime = startTime;
	}

	public long getDuration() {
		return this.duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	public int getParticipants() {
		return this.participants;
	}

	public void setParticipants(int participants) {
		this.participants = participants;
	}

	public Set<GymTrainer> getTrainers() {
		return this.trainers;
	}

	public void setTrainers(Set<GymTrainer> trainers) {
		this.trainers = trainers;
	}

}
