package pl.tzaras.fitness.manager.db.data;

// Generated Nov 17, 2013 7:59:56 PM by Hibernate Tools 4.0.0

/**
 * GymClassType generated by hbm2java
 */
public class GymClassType implements java.io.Serializable {

	private long classId;
	private String name;

	public GymClassType() {
	}

	public GymClassType(String name) {
		this.name = name;
	}

	public GymClassType(long classId, String name) {
		this.classId = classId;
		this.name = name;
	}

	public long getClassId() {
		return this.classId;
	}

	public void setClassId(long classId) {
		this.classId = classId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
