package pl.tzaras.fitness.manager.db.data;

// Generated Nov 17, 2013 7:59:56 PM by Hibernate Tools 4.0.0

import org.joda.time.DateTime;

/**
 * GymClass generated by hbm2java
 */
public class GymClass implements java.io.Serializable {

	private long classId;
	private GymRoom classRoom;
	private GymClassType classType;
	private GymTrainer classTrainer1;
	private GymTrainer classTrainer2;
	private GymTrainer classTrainer3;
	private GymTrainer classTrainer4;
	private GymTrainer classTrainer5;
	private DateTime startTime;
	private long duration;
	private int participants;

	public GymClass() {
	}

	public GymClass(GymRoom classRoom, GymClassType classType, GymTrainer classTrainer1) {
		this.classRoom = classRoom;
		this.classType = classType;
		this.classTrainer1 = classTrainer1;
	}

	public GymClass(GymRoom classRoom, GymClassType classType, GymTrainer classTrainer1,
			GymTrainer classTrainer2, GymTrainer classTrainer3, GymTrainer classTrainer4,
			GymTrainer classTrainer5, DateTime startTime, long duration, int participants) {
		this.classRoom = classRoom;
		this.classType = classType;
		this.classTrainer1 = classTrainer1;
		this.classTrainer2 = classTrainer2;
		this.classTrainer3 = classTrainer3;
		this.classTrainer4 = classTrainer4;
		this.classTrainer5 = classTrainer5;
		this.startTime = startTime;
		this.duration = duration;
		this.participants = participants;
	}

	public long getClassId() {
		return this.classId;
	}

	public void setClassId(long classId) {
		this.classId = classId;
	}

	public GymRoom getClassRoom() {
		return this.classRoom;
	}

	public void setClassRoom(GymRoom classRoom) {
		this.classRoom = classRoom;
	}

	public GymClassType getClassType() {
		return this.classType;
	}

	public void setClassType(GymClassType classType) {
		this.classType = classType;
	}

	public GymTrainer getClassTrainer1() {
		return this.classTrainer1;
	}

	public void setClassTrainer1(GymTrainer classTrainer1) {
		this.classTrainer1 = classTrainer1;
	}

	public GymTrainer getClassTrainer2() {
		return this.classTrainer2;
	}

	public void setClassTrainer2(GymTrainer classTrainer2) {
		this.classTrainer2 = classTrainer2;
	}

	public GymTrainer getClassTrainer3() {
		return this.classTrainer3;
	}

	public void setClassTrainer3(GymTrainer classTrainer3) {
		this.classTrainer3 = classTrainer3;
	}

	public GymTrainer getClassTrainer4() {
		return this.classTrainer4;
	}

	public void setClassTrainer4(GymTrainer classTrainer4) {
		this.classTrainer4 = classTrainer4;
	}

	public GymTrainer getClassTrainer5() {
		return this.classTrainer5;
	}

	public void setClassTrainer5(GymTrainer classTrainer5) {
		this.classTrainer5 = classTrainer5;
	}

	public DateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(DateTime startTime) {
		this.startTime = startTime;
	}

	public long getDuration() {
		return this.duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	public int getParticipants() {
		return this.participants;
	}

	public void setParticipants(int participants) {
		this.participants = participants;
	}

}
