package pl.tzaras.fitness.manager.db.data;

// Generated Oct 13, 2013 8:20:36 PM by Hibernate Tools 3.4.0.CR1

import org.jadira.usertype.dateandtime.joda.PersistentDateTime;
import org.joda.time.DateTime;

/**
 * GymClass generated by hbm2java
 */
public class GymClass implements java.io.Serializable {

	private long classId;
	private GymRoom classRoom;
	private GymTrainer classTrainer;
	private GymClassType classType;
	private DateTime startTime;
	private long duration;
	private int participants;

	public GymClass() {
	}

	public GymClass(GymRoom classRoom, GymTrainer classTrainer,
			GymClassType classType) {
		this.classRoom = classRoom;
		this.classTrainer = classTrainer;
		this.classType = classType;
	}

	public GymClass(GymRoom classRoom, GymTrainer classTrainer,
			GymClassType classType, DateTime startTime,
			long duration, int participants) {
		this.classRoom = classRoom;
		this.classTrainer = classTrainer;
		this.classType = classType;
		this.startTime = startTime;
		this.duration = duration;
		this.participants = participants;
	}

	public long getClassId() {
		return this.classId;
	}

	public void setClassId(long classId) {
		this.classId = classId;
	}

	public GymRoom getClassRoom() {
		return this.classRoom;
	}

	public void setClassRoom(GymRoom classRoom) {
		this.classRoom = classRoom;
	}

	public GymTrainer getClassTrainer() {
		return this.classTrainer;
	}

	public void setClassTrainer(GymTrainer classTrainer) {
		this.classTrainer = classTrainer;
	}

	public GymClassType getClassType() {
		return this.classType;
	}

	public void setClassType(GymClassType classType) {
		this.classType = classType;
	}

	public DateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(DateTime startTime) {
		this.startTime = startTime;
	}

	public long getDuration() {
		return this.duration;
	}

	public void setDuration(long duration) {
		this.duration = duration;
	}

	public int getParticipants() {
		return this.participants;
	}

	public void setParticipants(int participants) {
		this.participants = participants;
	}

}
