package pl.tzaras.fitness.manager.db.data;

// Generated Oct 10, 2013 6:42:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * GymRoom generated by hbm2java
 */
public class GymRoom implements java.io.Serializable {

	private long ID;
	private String name;

	public GymRoom() {
	}

	public GymRoom(String name) {
		this.name = name;
	}

	public long getID() {
		return this.ID;
	}

	public void setID(long ID) {
		this.ID = ID;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
