package pl.tzaras.fitness.manager.db.data;

// Generated Nov 11, 2013 11:05:25 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * GymTrainer generated by hbm2java
 */
public class GymTrainer implements java.io.Serializable {

	private long trainerId;
	private String name;
	private String surrname;
	private double rateOfPay;
	private Set<GymClass> classes = new HashSet<GymClass>(0);

	public GymTrainer() {
	}

	public GymTrainer(String name, String surrname, double rateOfPay, Set<GymClass> classes) {
		this.name = name;
		this.surrname = surrname;
		this.rateOfPay = rateOfPay;
		this.classes = classes;
	}

	public long getTrainerId() {
		return this.trainerId;
	}

	public void setTrainerId(long trainerId) {
		this.trainerId = trainerId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurrname() {
		return this.surrname;
	}

	public void setSurrname(String surrname) {
		this.surrname = surrname;
	}

	public double getRateOfPay() {
		return this.rateOfPay;
	}

	public void setRateOfPay(double rateOfPay) {
		this.rateOfPay = rateOfPay;
	}

	public Set<GymClass> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<GymClass> classes) {
		this.classes = classes;
	}

}
